FROM python

RUN mkdir -p /app

WORKDIR app

RUN git clone https://github.com/TakedoDev/garpix-site.git .
RUN git checkout remotes/origin/main

RUN cp src/example.env .env
RUN pip install -r src/requirements.txt
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6 -y

WORKDIR src

RUN python backend/manage.py makemigrations
RUN python backend/manage.py migrate

EXPOSE 8000

CMD ["python", "backend/manage.py", "runserver", "0.0.0.0:8000"]